### ISSUE TITLE
Elasticsearch 2.0 scripting: Invoke custom script from plugin

### ISSUE THREAD

**Issue by haingo-kenshjn** [imotov/elasticsearch-native-script-example#21]
Can someone help me with this question.
If we defined native script in plugin: com.test.nativescript.TestScript, can we invoke that package inside another groovy script and create new instance ?

Ex: 
inside config/scripts/test.groovy:

import  com.test.nativescript.TestScript;

def testScript = new TestScript();
Result: "startup failed:\r\nc78a82bc96ca7751e83e256b4ee0c322cda13bea: 1: unable to resolve com.test.nativescript.TestScript"

**Comment by imotov** [comment]
@haingo-kenshjn It's typically better to ask questions like this on [Elastics discussion forum](https://discuss.elastic.co/). Saying that, I don't think it's possible to access a native script from a groovy script since groovy script is running in an isolated groovy-code only class loader that prevents it from accessing arbitrary classes.

**Comment by haingo-kenshjn** [comment]
thank for your answer.
