### ISSUE TITLE
Confused about versioning

### ISSUE THREAD

**Issue by acampagna** [imotov/elasticsearch-native-script-example#24]
The readme files make this a bit confusing because in master it says use 2.x. But then when you goto 2.x it says use master for "2.1.0 and above".

Is master for the latest ES 2.x (2.3.4) release or is it for ES 5.0 (might have been named ES3.0 when you last updated the project)?

**Comment by imotov** [comment]
The master branch of this plugin was tracking the master branch of elasticsearch when it was 3.0 but it is not in active development any more because I am in the process of moving this example into the main elasticsearch project. The PR is in the review process and can be found here - elastic/elasticsearch/pull/19334 When this PR is merged I will probably remove the master branch here and only leave 2.x and 1.x branches for historical reasons.

**Comment by acampagna** [comment]
Thank you very much. That makes perfect sense.

**Comment by mtraynham** [comment]
@imotov I guess you closed it.  

I'm curious, if you were to recreate the lookupIndex function for 5.0, how would you go about it, i.e. how would you pass a NodeClient to the script factory?  I'd somewhat like'd to retain this functionality, so if you have any suggestions, that would be awesome.
