### ISSUE TITLE
porting to script engine

### ISSUE THREAD

**Issue by a4180p** [imotov/elasticsearch-native-script-example#31]
HI @imotov 
Is there any chance that these examples will be ported to script engine?

**Comment by imotov** [comment]
I considered that, but many of these examples either cannot be ported to 6.0.0, because of some restrictions and changes in API or don't make much sense in 6.0.0. So, I abandoned this idea. If you have some particular question or need an example of some particular functionally we can talk about it in the elastic's [discussion forum](https://discuss.elastic.co/c/elasticsearch) (или [тут](https://discuss.elastic.co/c/in-your-native-tongue/15-category) если вы предпочитаете русский)  and we will try to figure something out.
